### ISSUE TITLE
Unclear error message when using a wrong device name

### ISSUE THREAD

**Issue by wupengc** [kdavyd/ebs-playground#3]
I'm using a wrong device name as the download command, it print a stack, but it's not clear that my device is wrong.
If would helpful if it has a check up-front.
for example, "/dev/nvme1" is a wrong device name, I got below error stack.

```
python3 ebs.py download snap-06915b95caexxxxx /dev/nvme1
[5:21](https://amzn-aws.slack.com/archives/D03BV5NQGDD/p1650489691544959)
I tried above command, it failed
Snapshot snap-06915b95cae76c31c contains 3914 chunks and 2052063232 bytes, took 0.62 seconds.
['/dev/nvme1']
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
  r = call_item()
 File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
  return self.fn(*self.args, **self.kwargs)
 File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
  return self.func(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
  for func, args, kwargs in self.items]
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
  for func, args, kwargs in self.items]
 File "ebs.py", line 191, in get_blocks
  parallel2(delayed(get_block)(block, ebs, files) for block in array)
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 1056, in __call__
  self.retrieve()
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 935, in retrieve
  self._output.extend(job.get(timeout=self.timeout))
 File "/usr/lib64/python3.7/multiprocessing/pool.py", line 657, in get
  raise self._value
 File "/usr/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
  result = (True, func(*args, **kwds))
 File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
  return self.func(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
  for func, args, kwargs in self.items]
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
  for func, args, kwargs in self.items]
 File "ebs.py", line 117, in get_block
  with os.fdopen(os.open(file, os.O_RDWR | os.O_CREAT), 'rb+') as f:
 File "/usr/lib64/python3.7/os.py", line 1029, in fdopen
  return io.open(fd, *args, **kwargs)
io.UnsupportedOperation: File or stream is not seekable.
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
 File "ebs.py", line 334, in <module>
  main()
 File "ebs.py", line 265, in main
  parallel(delayed(get_blocks)(array, files) for array in split)
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 1056, in __call__
  self.retrieve()
 File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 935, in retrieve
  self._output.extend(job.get(timeout=self.timeout))
 File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
  return future.result(timeout=timeout)
 File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
  return self.__get_result()
 File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
  raise self._exception
io.UnsupportedOperation: File or stream is not seekable.
```

**Comment by kdavyd** [comment]
Fixed in https://github.com/kdavyd/ebs-playground/commit/c5f9d1f620b47412ddc959b75266d982374fad53
